config:
  servername: default
  info: This is default sever
  user: user001
  password: password001
  accessmessage: default msg - spring cloud config data
---

spring:
  profiles: develop
config:
  servername: develop
  info: This is develop sever
  user: user002
  password: password002
  accessmessage: welcome to develop server Android RabbitMQ!

---

spring:
  profiles: production
config:
  servername: production
  info: This is production sever
  user: user003
  password: password003
  accessmessage: welcome to production server
